name: Deploy PatientPath to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to PatientPath VPS
      uses: appleboy/ssh-action@master
      with:
        host: patientpath.org
        username: root
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        script: |
          cd /var/www/patient-path
          git pull origin main
          
          # Create or update the .env file
          cat > /var/www/patient-path/frontend/.env << EOL
          REACT_APP_SUPABASE_URL=https://mtrmxzywxfklltwuxtgb.supabase.co
          REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cm14enl3eGZrbGx0d3V4dGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NzEwMzksImV4cCI6MjA1NzA0NzAzOX0.WO9gM5kfhIvLiS7PNbbAmayYKfpPiCocahyXAUtTcdY
          REACT_APP_API_URL=/api
          EOL
          
          # Install dependencies and build
          cd backend && npm install
          cd ../frontend && npm install && npm run build
          
          # Restart the API server
          pm2 restart patient-path-api || pm2 start ecosystem.config.js